<!DOCTYPE html>
<?php

session_start();

require("../account/authconnect.php");

$sessionEmail = $_SESSION['email'];
$uid = $auth->getUID($sessionEmail);

if (!$_SESSION['logged_in']) {
    //shows login button
    $value = 'Login';
    $href = '../account/';
} else {
    //shows profile button
    $value = 'Logout';
    $href = '../account/logout.php';
}

?>

<html lang="en">
    <head>
        <meta charset="utf-8">    
        <meta name="viewport" content="width=device-width, initial-scale=1">
          <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
          <style>
          .navbar {
            margin-bottom: 0;
            border-radius: 0;
            background-color: #006400;
            color: #FFFF;
            padding: 1% 0;
            font-size: 1.2em;
            border: 0;
          }
          .navbar-brand{
            float:left;
            min-height: 55px;
            padding: 0 15px 5px;
          }
        .navbar-inverse .navbar-nav .active a,
        .navbar-inverse .navbar-nav .active a:focus,
        .navbar-inverse .navbar-nav .active a:hover{
          color: #FFF;
          background-color: #006400;
        }

        </style>
        <link rel="stylesheet" type="text/css" href="mystyle.css">
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
           integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ=="
           crossorigin=""/>
        <title>Pinamals</title>
    </head>
    
    <body>
    
    <!-- The Modal -->
    <div id="myModal" class="modal">

      <!-- Modal content -->
      <div class="modal-content">
        <div class="modal-header">
          <span class="close">&times;</span>
          <h2>Add A Sighting</h2>
        </div>
        <div class="modal-body">
         
          <form action="file.php" method="POST" enctype="multipart/form-data">
          <p>Category</p>
            <input name = "Category">
          <p>Species</p>
            <select name="Species">
            <option value="aardwolf">Aardwolf</option>
<option value="admiral, indian red">Admiral, indian red</option>
<option value="adouri (unidentified)">Adouri (unidentified)</option>
<option value="african black crake">African black crake</option>
<option value="african buffalo">African buffalo</option>
<option value="african bush squirrel">African bush squirrel</option>
<option value="african clawless otter">African clawless otter</option>
<option value="african darter">African darter</option>
<option value="african elephant">African elephant</option>
<option value="african fish eagle">African fish eagle</option>
<option value="african ground squirrel (unidentified)">African ground squirrel (unidentified)</option>
<option value="african jacana">African jacana</option>
<option value="african lion">African lion</option>
<option value="african lynx">African lynx</option>
<option value="african pied wagtail">African pied wagtail</option>
<option value="african polecat">African polecat</option>
<option value="african porcupine">African porcupine</option>
<option value="african red-eyed bulbul">African red-eyed bulbul</option>
<option value="african skink">African skink</option>
<option value="african snake (unidentified)">African snake (unidentified)</option>
<option value="african wild cat">African wild cat</option>
<option value="african wild dog">African wild dog</option>
<option value="agama lizard (unidentified)">Agama lizard (unidentified)</option>
<option value="agile wallaby">Agile wallaby</option>
<option value="agouti">Agouti</option>
<option value="albatross, galapagos">Albatross, galapagos</option>
<option value="albatross, waved">Albatross, waved</option>
<option value="alligator, american">Alligator, american</option>
<option value="alligator, mississippi">Alligator, mississippi</option>
<option value="alpaca">Alpaca</option>
<option value="amazon parrot (unidentified)">Amazon parrot (unidentified)</option>
<option value="american virginia opossum">American Virginia opossum</option>
<option value="american alligator">American alligator</option>
<option value="american badger">American badger</option>
<option value="american beaver">American beaver</option>
<option value="american bighorn sheep">American bighorn sheep</option>
<option value="american bison">American bison</option>
<option value="american black bear">American black bear</option>
<option value="american buffalo">American buffalo</option>
<option value="american crow">American crow</option>
<option value="american marten">American marten</option>
<option value="american racer">American racer</option>
<option value="american woodcock">American woodcock</option>
<option value="anaconda (unidentified)">Anaconda (unidentified)</option>
<option value="andean goose">Andean goose</option>
<option value="ant (unidentified)">Ant (unidentified)</option>
<option value="anteater, australian spiny">Anteater, australian spiny</option>
<option value="anteater, giant">Anteater, giant</option>
<option value="antechinus, brown">Antechinus, brown</option>
<option value="antelope ground squirrel">Antelope ground squirrel</option>
<option value="antelope, four-horned">Antelope, four-horned</option>
<option value="antelope, roan">Antelope, roan</option>
<option value="antelope, sable">Antelope, sable</option>
<option value="arboral spiny rat">Arboral spiny rat</option>
<option value="arctic fox">Arctic fox</option>
<option value="arctic ground squirrel">Arctic ground squirrel</option>
<option value="arctic hare">Arctic hare</option>
<option value="arctic lemming">Arctic lemming</option>
<option value="arctic tern">Arctic tern</option>
<option value="argalis">Argalis</option>
<option value="armadillo, common long-nosed">Armadillo, common long-nosed</option>
<option value="armadillo, giant">Armadillo, giant</option>
<option value="armadillo, nine-banded">Armadillo, nine-banded</option>
<option value="armadillo, seven-banded">Armadillo, seven-banded</option>
<option value="asian elephant">Asian elephant</option>
<option value="asian false vampire bat">Asian false vampire bat</option>
<option value="asian foreset tortoise">Asian foreset tortoise</option>
<option value="asian lion">Asian lion</option>
<option value="asian openbill">Asian openbill</option>
<option value="asian red fox">Asian red fox</option>
<option value="asian water buffalo">Asian water buffalo</option>
<option value="asian water dragon">Asian water dragon</option>
<option value="asiatic jackal">Asiatic jackal</option>
<option value="asiatic wild ass">Asiatic wild ass</option>
<option value="ass, asiatic wild">Ass, asiatic wild</option>
<option value="australian brush turkey">Australian brush turkey</option>
<option value="australian magpie">Australian magpie</option>
<option value="australian masked owl">Australian masked owl</option>
<option value="australian pelican">Australian pelican</option>
<option value="australian sea lion">Australian sea lion</option>
<option value="australian spiny anteater">Australian spiny anteater</option>
<option value="avocet, pied">Avocet, pied</option>
<option value="azara's zorro">Azara's zorro</option>
<option value="baboon, chacma">Baboon, chacma</option>
<option value="baboon, gelada">Baboon, gelada</option>
<option value="baboon, olive">Baboon, olive</option>
<option value="baboon, savanna">Baboon, savanna</option>
<option value="baboon, yellow">Baboon, yellow</option>
<option value="badger, american">Badger, american</option>
<option value="badger, eurasian">Badger, eurasian</option>
<option value="badger, european">Badger, european</option>
<option value="badger, honey">Badger, honey</option>
<option value="bahama pintail">Bahama pintail</option>
<option value="bald eagle">Bald eagle</option>
<option value="baleen whale">Baleen whale</option>
<option value="banded mongoose">Banded mongoose</option>
<option value="bandicoot, long-nosed">Bandicoot, long-nosed</option>
<option value="bandicoot, short-nosed">Bandicoot, short-nosed</option>
<option value="bandicoot, southern brown">Bandicoot, southern brown</option>
<option value="barasingha deer">Barasingha deer</option>
<option value="barbet, black-collared">Barbet, black-collared</option>
<option value="barbet, crested">Barbet, crested</option>
<option value="barbet, levaillant's">Barbet, levaillant's</option>
<option value="bare-faced go away bird">Bare-faced go away bird</option>
<option value="barking gecko">Barking gecko</option>
<option value="barrows goldeneye">Barrows goldeneye</option>
<option value="bat, asian false vampire">Bat, asian false vampire</option>
<option value="bat, little brown">Bat, little brown</option>
<option value="bat, madagascar fruit">Bat, madagascar fruit</option>
<option value="bat-eared fox">Bat-eared fox</option>
<option value="bateleur eagle">Bateleur eagle</option>
<option value="bear, american black">Bear, american black</option>
<option value="bear, black">Bear, black</option>
<option value="bear, grizzly">Bear, grizzly</option>
<option value="bear, polar">Bear, polar</option>
<option value="bear, sloth">Bear, sloth</option>
<option value="beaver, american">Beaver, american</option>
<option value="beaver, eurasian">Beaver, eurasian</option>
<option value="beaver, european">Beaver, european</option>
<option value="beaver, north american">Beaver, north american</option>
<option value="bee-eater (unidentified)">Bee-eater (unidentified)</option>
<option value="bee-eater, carmine">Bee-eater, carmine</option>
<option value="bee-eater, nubian">Bee-eater, nubian</option>
<option value="bee-eater, white-fronted">Bee-eater, white-fronted</option>
<option value="beisa oryx">Beisa oryx</option>
<option value="bengal vulture">Bengal vulture</option>
<option value="bennett's wallaby">Bennett's wallaby</option>
<option value="bent-toed gecko">Bent-toed gecko</option>
<option value="bettong, brush-tailed">Bettong, brush-tailed</option>
<option value="bird (unidentified)">Bird (unidentified)</option>
<option value="bird, bare-faced go away">Bird, bare-faced go away</option>
<option value="bird, black-throated butcher">Bird, black-throated butcher</option>
<option value="bird, magnificent frigate">Bird, magnificent frigate</option>
<option value="bird, pied butcher">Bird, pied butcher</option>
<option value="bird, red-billed tropic">Bird, red-billed tropic</option>
<option value="bird, secretary">Bird, secretary</option>
<option value="bison, american">Bison, american</option>
<option value="black and white colobus">Black and white colobus</option>
<option value="black bear">Black bear</option>
<option value="black curlew">Black curlew</option>
<option value="black kite">Black kite</option>
<option value="black rhinoceros">Black rhinoceros</option>
<option value="black spider monkey">Black spider monkey</option>
<option value="black swan">Black swan</option>
<option value="black vulture">Black vulture</option>
<option value="black-backed jackal">Black-backed jackal</option>
<option value="black-backed magpie">Black-backed magpie</option>
<option value="black-capped capuchin">Black-capped capuchin</option>
<option value="black-capped chickadee">Black-capped chickadee</option>
<option value="black-cheeked waxbill">Black-cheeked waxbill</option>
<option value="black-collared barbet">Black-collared barbet</option>
<option value="black-crowned crane">Black-crowned crane</option>
<option value="black-crowned night heron">Black-crowned night heron</option>
<option value="black-eyed bulbul">Black-eyed bulbul</option>
<option value="black-faced kangaroo">Black-faced kangaroo</option>
<option value="black-footed ferret">Black-footed ferret</option>
<option value="black-fronted bulbul">Black-fronted bulbul</option>
<option value="black-necked stork">Black-necked stork</option>
<option value="black-tailed deer">Black-tailed deer</option>
<option value="black-tailed prairie dog">Black-tailed prairie dog</option>
<option value="black-tailed tree creeper">Black-tailed tree creeper</option>
<option value="black-throated butcher bird">Black-throated butcher bird</option>
<option value="black-throated cardinal">Black-throated cardinal</option>
<option value="black-winged stilt">Black-winged stilt</option>
<option value="blackbird, red-winged">Blackbird, red-winged</option>
<option value="blackbuck">Blackbuck</option>
<option value="blackish oystercatcher">Blackish oystercatcher</option>
<option value="blacksmith plover">Blacksmith plover</option>
<option value="bleeding heart monkey">Bleeding heart monkey</option>
<option value="blesbok">Blesbok</option>
<option value="bleu, blue-breasted cordon">Bleu, blue-breasted cordon</option>
<option value="bleu, red-cheeked cordon">Bleu, red-cheeked cordon</option>
<option value="blue and gold macaw">Blue and gold macaw</option>
<option value="blue and yellow macaw">Blue and yellow macaw</option>
<option value="blue catfish">Blue catfish</option>
<option value="blue crane">Blue crane</option>
<option value="blue duck">Blue duck</option>
<option value="blue fox">Blue fox</option>
<option value="blue peacock">Blue peacock</option>
<option value="blue racer">Blue racer</option>
<option value="blue shark">Blue shark</option>
<option value="blue waxbill">Blue waxbill</option>
<option value="blue wildebeest">Blue wildebeest</option>
<option value="blue-breasted cordon bleu">Blue-breasted cordon bleu</option>
<option value="blue-faced booby">Blue-faced booby</option>
<option value="blue-footed booby">Blue-footed booby</option>
<option value="blue-tongued lizard">Blue-tongued lizard</option>
<option value="blue-tongued skink">Blue-tongued skink</option>
<option value="boa, columbian rainbow">Boa, columbian rainbow</option>
<option value="boa, cook's tree">Boa, cook's tree</option>
<option value="boa, emerald green tree">Boa, emerald green tree</option>
<option value="boa, malagasy ground">Boa, malagasy ground</option>
<option value="boa, mexican">Boa, mexican</option>
<option value="boar, wild">Boar, wild</option>
<option value="boat-billed heron">Boat-billed heron</option>
<option value="bobcat">Bobcat</option>
<option value="bohor reedbuck">Bohor reedbuck</option>
<option value="bonnet macaque">Bonnet macaque</option>
<option value="bontebok">Bontebok</option>
<option value="booby, blue-faced">Booby, blue-faced</option>
<option value="booby, blue-footed">Booby, blue-footed</option>
<option value="booby, masked">Booby, masked</option>
<option value="bottle-nose dolphin">Bottle-nose dolphin</option>
<option value="boubou, southern">Boubou, southern</option>
<option value="brazilian otter">Brazilian otter</option>
<option value="brazilian tapir">Brazilian tapir</option>
<option value="brindled gnu">Brindled gnu</option>
<option value="brocket, brown">Brocket, brown</option>
<option value="brocket, red">Brocket, red</option>
<option value="brolga crane">Brolga crane</option>
<option value="brown and yellow marshbird">Brown and yellow marshbird</option>
<option value="brown antechinus">Brown antechinus</option>
<option value="brown brocket">Brown brocket</option>
<option value="brown capuchin">Brown capuchin</option>
<option value="brown hyena">Brown hyena</option>
<option value="brown lemur">Brown lemur</option>
<option value="brown pelican">Brown pelican</option>
<option value="brush-tailed bettong">Brush-tailed bettong</option>
<option value="brush-tailed phascogale">Brush-tailed phascogale</option>
<option value="brush-tailed rat kangaroo">Brush-tailed rat kangaroo</option>
<option value="buffalo, african">Buffalo, african</option>
<option value="buffalo, american">Buffalo, american</option>
<option value="buffalo, asian water">Buffalo, asian water</option>
<option value="buffalo, wild water">Buffalo, wild water</option>
<option value="bulbul, african red-eyed">Bulbul, african red-eyed</option>
<option value="bulbul, black-eyed">Bulbul, black-eyed</option>
<option value="bulbul, black-fronted">Bulbul, black-fronted</option>
<option value="bunting, crested">Bunting, crested</option>
<option value="burchell's gonolek">Burchell's gonolek</option>
<option value="burmese black mountain tortoise">Burmese black mountain tortoise</option>
<option value="burmese brown mountain tortoise">Burmese brown mountain tortoise</option>
<option value="burrowing owl">Burrowing owl</option>
<option value="bush dog">Bush dog</option>
<option value="bushbaby, large-eared">Bushbaby, large-eared</option>
<option value="bushbuck">Bushbuck</option>
<option value="bushpig">Bushpig</option>
<option value="bustard, denham's">Bustard, denham's</option>
<option value="bustard, kori">Bustard, kori</option>
<option value="bustard, stanley">Bustard, stanley</option>
<option value="butterfly (unidentified)">Butterfly (unidentified)</option>
<option value="butterfly, canadian tiger swallowtail">Butterfly, canadian tiger swallowtail</option>
<option value="butterfly, tropical buckeye">Butterfly, tropical buckeye</option>
<option value="buttermilk snake">Buttermilk snake</option>
<option value="caiman, spectacled">Caiman, spectacled</option>
<option value="california sea lion">California sea lion</option>
<option value="camel, dromedary">Camel, dromedary</option>
<option value="campo flicker">Campo flicker</option>
<option value="canada goose">Canada goose</option>
<option value="canadian river otter">Canadian river otter</option>
<option value="canadian tiger swallowtail butterfly">Canadian tiger swallowtail butterfly</option>
<option value="cape barren goose">Cape Barren goose</option>
<option value="cape clawless otter">Cape clawless otter</option>
<option value="cape cobra">Cape cobra</option>
<option value="cape fox">Cape fox</option>
<option value="cape raven">Cape raven</option>
<option value="cape starling">Cape starling</option>
<option value="cape white-eye">Cape white-eye</option>
<option value="cape wild cat">Cape wild cat</option>
<option value="capuchin, black-capped">Capuchin, black-capped</option>
<option value="capuchin, brown">Capuchin, brown</option>
<option value="capuchin, weeper">Capuchin, weeper</option>
<option value="capuchin, white-fronted">Capuchin, white-fronted</option>
<option value="capybara">Capybara</option>
<option value="caracal">Caracal</option>
<option value="caracara (unidentified)">Caracara (unidentified)</option>
<option value="caracara, yellow-headed">Caracara, yellow-headed</option>
<option value="cardinal, black-throated">Cardinal, black-throated</option>
<option value="cardinal, red-capped">Cardinal, red-capped</option>
<option value="caribou">Caribou</option>
<option value="carmine bee-eater">Carmine bee-eater</option>
<option value="carpet python">Carpet python</option>
<option value="carpet snake">Carpet snake</option>
<option value="cat, african wild">Cat, african wild</option>
<option value="cat, cape wild">Cat, cape wild</option>
<option value="cat, civet">Cat, civet</option>
<option value="cat, european wild">Cat, european wild</option>
<option value="cat, jungle">Cat, jungle</option>
<option value="cat, kaffir">Cat, kaffir</option>
<option value="cat, long-tailed spotted">Cat, long-tailed spotted</option>
<option value="cat, miner's">Cat, miner's</option>
<option value="cat, native">Cat, native</option>
<option value="cat, ringtail">Cat, ringtail</option>
<option value="cat, tiger">Cat, tiger</option>
<option value="cat, toddy">Cat, toddy</option>
<option value="catfish, blue">Catfish, blue</option>
<option value="cattle egret">Cattle egret</option>
<option value="cereopsis goose">Cereopsis goose</option>
<option value="chacma baboon">Chacma baboon</option>
<option value="chameleon (unidentified)">Chameleon (unidentified)</option>
<option value="cheetah">Cheetah</option>
<option value="chestnut weaver">Chestnut weaver</option>
<option value="chickadee, black-capped">Chickadee, black-capped</option>
<option value="chilean flamingo">Chilean flamingo</option>
<option value="chimpanzee">Chimpanzee</option>
<option value="chipmunk, least">Chipmunk, least</option>
<option value="chital">Chital</option>
<option value="chuckwalla">Chuckwalla</option>
<option value="civet (unidentified)">Civet (unidentified)</option>
<option value="civet cat">Civet cat</option>
<option value="civet, common palm">Civet, common palm</option>
<option value="civet, small-toothed palm">Civet, small-toothed palm</option>
<option value="clark's nutcracker">Clark's nutcracker</option>
<option value="cliffchat, mocking">Cliffchat, mocking</option>
<option value="coatimundi, ring-tailed">Coatimundi, ring-tailed</option>
<option value="coatimundi, white-nosed">Coatimundi, white-nosed</option>
<option value="cobra (unidentified)">Cobra (unidentified)</option>
<option value="cobra, cape">Cobra, cape</option>
<option value="cobra, egyptian">Cobra, egyptian</option>
<option value="cockatoo, long-billed">Cockatoo, long-billed</option>
<option value="cockatoo, red-breasted">Cockatoo, red-breasted</option>
<option value="cockatoo, red-tailed">Cockatoo, red-tailed</option>
<option value="cockatoo, roseate">Cockatoo, roseate</option>
<option value="cockatoo, slender-billed">Cockatoo, slender-billed</option>
<option value="cockatoo, sulfur-crested">Cockatoo, sulfur-crested</option>
<option value="coke's hartebeest">Coke's hartebeest</option>
<option value="collared lemming">Collared lemming</option>
<option value="collared lizard">Collared lizard</option>
<option value="collared peccary">Collared peccary</option>
<option value="colobus, black and white">Colobus, black and white</option>
<option value="colobus, magistrate black">Colobus, magistrate black</option>
<option value="colobus, white-mantled">Colobus, white-mantled</option>
<option value="columbian rainbow boa">Columbian rainbow boa</option>
<option value="comb duck">Comb duck</option>
<option value="common boubou shrike">Common boubou shrike</option>
<option value="common brushtail possum">Common brushtail possum</option>
<option value="common dolphin">Common dolphin</option>
<option value="common duiker">Common duiker</option>
<option value="common eland">Common eland</option>
<option value="common genet">Common genet</option>
<option value="common goldeneye">Common goldeneye</option>
<option value="common green iguana">Common green iguana</option>
<option value="common grenadier">Common grenadier</option>
<option value="common langur">Common langur</option>
<option value="common long-nosed armadillo">Common long-nosed armadillo</option>
<option value="common melba finch">Common melba finch</option>
<option value="common mynah">Common mynah</option>
<option value="common nighthawk">Common nighthawk</option>
<option value="common palm civet">Common palm civet</option>
<option value="common pheasant">Common pheasant</option>
<option value="common raccoon">Common raccoon</option>
<option value="common rhea">Common rhea</option>
<option value="common ringtail">Common ringtail</option>
<option value="common seal">Common seal</option>
<option value="common shelduck">Common shelduck</option>
<option value="common turkey">Common turkey</option>
<option value="common wallaroo">Common wallaroo</option>
<option value="common waterbuck">Common waterbuck</option>
<option value="common wolf">Common wolf</option>
<option value="common wombat">Common wombat</option>
<option value="common zebra">Common zebra</option>
<option value="common zorro">Common zorro</option>
<option value="constrictor, eastern boa">Constrictor, eastern boa</option>
<option value="cook's tree boa">Cook's tree boa</option>
<option value="coot, red-knobbed">Coot, red-knobbed</option>
<option value="coqui francolin">Coqui francolin</option>
<option value="coqui partridge">Coqui partridge</option>
<option value="corella, long-billed">Corella, long-billed</option>
<option value="cormorant (unidentified)">Cormorant (unidentified)</option>
<option value="cormorant, flightless">Cormorant, flightless</option>
<option value="cormorant, great">Cormorant, great</option>
<option value="cormorant, javanese">Cormorant, javanese</option>
<option value="cormorant, king">Cormorant, king</option>
<option value="cormorant, large">Cormorant, large</option>
<option value="cormorant, little">Cormorant, little</option>
<option value="cormorant, neotropic">Cormorant, neotropic</option>
<option value="cormorant, pied">Cormorant, pied</option>
<option value="cottonmouth">Cottonmouth</option>
<option value="cougar">Cougar</option>
<option value="cow, scottish highland">Cow, scottish highland</option>
<option value="coyote">Coyote</option>
<option value="crab (unidentified)">Crab (unidentified)</option>
<option value="crab, red lava">Crab, red lava</option>
<option value="crab, sally lightfoot">Crab, sally lightfoot</option>
<option value="crab-eating fox">Crab-eating fox</option>
<option value="crab-eating raccoon">Crab-eating raccoon</option>
<option value="crake, african black">Crake, african black</option>
<option value="crane, black-crowned">Crane, black-crowned</option>
<option value="crane, blue">Crane, blue</option>
<option value="crane, brolga">Crane, brolga</option>
<option value="crane, sandhill">Crane, sandhill</option>
<option value="crane, sarus">Crane, sarus</option>
<option value="crane, stanley">Crane, stanley</option>
<option value="crane, wattled">Crane, wattled</option>
<option value="creeper, black-tailed tree">Creeper, black-tailed tree</option>
<option value="crested barbet">Crested barbet</option>
<option value="crested bunting">Crested bunting</option>
<option value="crested porcupine">Crested porcupine</option>
<option value="crested screamer">Crested screamer</option>
<option value="crimson-breasted shrike">Crimson-breasted shrike</option>
<option value="crocodile, nile">Crocodile, nile</option>
<option value="crow, american">Crow, american</option>
<option value="crow, house">Crow, house</option>
<option value="crow, pied">Crow, pied</option>
<option value="crown of thorns starfish">Crown of thorns starfish</option>
<option value="crowned eagle">Crowned eagle</option>
<option value="crowned hawk-eagle">Crowned hawk-eagle</option>
<option value="cuis">Cuis</option>
<option value="curlew, black">Curlew, black</option>
<option value="currasow (unidentified)">Currasow (unidentified)</option>
<option value="curve-billed thrasher">Curve-billed thrasher</option>
<option value="dabchick">Dabchick</option>
<option value="dama wallaby">Dama wallaby</option>
<option value="dark-winged trumpeter">Dark-winged trumpeter</option>
<option value="darter, african">Darter, african</option>
<option value="darwin ground finch (unidentified)">Darwin ground finch (unidentified)</option>
<option value="dassie">Dassie</option>
<option value="deer, barasingha">Deer, barasingha</option>
<option value="deer, black-tailed">Deer, black-tailed</option>
<option value="deer, mule">Deer, mule</option>
<option value="deer, red">Deer, red</option>
<option value="deer, roe">Deer, roe</option>
<option value="deer, savannah">Deer, savannah</option>
<option value="deer, spotted">Deer, spotted</option>
<option value="deer, swamp">Deer, swamp</option>
<option value="deer, white-tailed">Deer, white-tailed</option>
<option value="defassa waterbuck">Defassa waterbuck</option>
<option value="denham's bustard">Denham's bustard</option>
<option value="desert kangaroo rat">Desert kangaroo rat</option>
<option value="desert spiny lizard">Desert spiny lizard</option>
<option value="desert tortoise">Desert tortoise</option>
<option value="devil, tasmanian">Devil, tasmanian</option>
<option value="dik, kirk's dik">Dik, kirk's dik</option>
<option value="dingo">Dingo</option>
<option value="dog, african wild">Dog, african wild</option>
<option value="dog, black-tailed prairie">Dog, black-tailed prairie</option>
<option value="dog, bush">Dog, bush</option>
<option value="dog, raccoon">Dog, raccoon</option>
<option value="dolphin, bottle-nose">Dolphin, bottle-nose</option>
<option value="dolphin, common">Dolphin, common</option>
<option value="dolphin, striped">Dolphin, striped</option>
<option value="dove, emerald-spotted wood">Dove, emerald-spotted wood</option>
<option value="dove, galapagos">Dove, galapagos</option>
<option value="dove, laughing">Dove, laughing</option>
<option value="dove, little brown">Dove, little brown</option>
<option value="dove, mourning collared">Dove, mourning collared</option>
<option value="dove, ring">Dove, ring</option>
<option value="dove, rock">Dove, rock</option>
<option value="dove, white-winged">Dove, white-winged</option>
<option value="downy woodpecker">Downy woodpecker</option>
<option value="dragon, asian water">Dragon, asian water</option>
<option value="dragon, frilled">Dragon, frilled</option>
<option value="dragon, komodo">Dragon, komodo</option>
<option value="dragon, netted rock">Dragon, netted rock</option>
<option value="dragon, ornate rock">Dragon, ornate rock</option>
<option value="dragon, western bearded">Dragon, western bearded</option>
<option value="dragonfly, russian">Dragonfly, russian</option>
<option value="dromedary camel">Dromedary camel</option>
<option value="drongo, fork-tailed">Drongo, fork-tailed</option>
<option value="duck, blue">Duck, blue</option>
<option value="duck, comb">Duck, comb</option>
<option value="duck, mountain">Duck, mountain</option>
<option value="duck, white-faced whistling">Duck, white-faced whistling</option>
<option value="duiker, common">Duiker, common</option>
<option value="duiker, gray">Duiker, gray</option>
<option value="dunnart, fat-tailed">Dunnart, fat-tailed</option>
<option value="dusky gull">Dusky gull</option>
<option value="dusky rattlesnake">Dusky rattlesnake</option>
<option value="eagle owl (unidentified)">Eagle owl (unidentified)</option>
<option value="eagle, african fish">Eagle, african fish</option>
<option value="eagle, bald">Eagle, bald</option>
<option value="eagle, bateleur">Eagle, bateleur</option>
<option value="eagle, crowned">Eagle, crowned</option>
<option value="eagle, golden">Eagle, golden</option>
<option value="eagle, long-crested hawk">Eagle, long-crested hawk</option>
<option value="eagle, pallas's fish">Eagle, pallas's fish</option>
<option value="eagle, tawny">Eagle, tawny</option>
<option value="eagle, white-bellied sea">Eagle, white-bellied sea</option>
<option value="eastern boa constrictor">Eastern boa constrictor</option>
<option value="eastern box turtle">Eastern box turtle</option>
<option value="eastern cottontail rabbit">Eastern cottontail rabbit</option>
<option value="eastern diamondback rattlesnake">Eastern diamondback rattlesnake</option>
<option value="eastern dwarf mongoose">Eastern dwarf mongoose</option>
<option value="eastern fox squirrel">Eastern fox squirrel</option>
<option value="eastern grey kangaroo">Eastern grey kangaroo</option>
<option value="eastern indigo snake">Eastern indigo snake</option>
<option value="eastern quoll">Eastern quoll</option>
<option value="eastern white pelican">Eastern white pelican</option>
<option value="echidna, short-beaked">Echidna, short-beaked</option>
<option value="egret, cattle">Egret, cattle</option>
<option value="egret, great">Egret, great</option>
<option value="egret, snowy">Egret, snowy</option>
<option value="egyptian cobra">Egyptian cobra</option>
<option value="egyptian goose">Egyptian goose</option>
<option value="egyptian viper">Egyptian viper</option>
<option value="egyptian vulture">Egyptian vulture</option>
<option value="eland, common">Eland, common</option>
<option value="elegant crested tinamou">Elegant crested tinamou</option>
<option value="elephant, african">Elephant, african</option>
<option value="elephant, asian">Elephant, asian</option>
<option value="eleven-banded armadillo (unidentified)">Eleven-banded armadillo (unidentified)</option>
<option value="elk, wapiti">Elk, Wapiti</option>
<option value="emerald green tree boa">Emerald green tree boa</option>
<option value="emerald-spotted wood dove">Emerald-spotted wood dove</option>
<option value="emu">Emu</option>
<option value="eurasian badger">Eurasian badger</option>
<option value="eurasian beaver">Eurasian beaver</option>
<option value="eurasian hoopoe">Eurasian hoopoe</option>
<option value="eurasian red squirrel">Eurasian red squirrel</option>
<option value="euro wallaby">Euro wallaby</option>
<option value="european badger">European badger</option>
<option value="european beaver">European beaver</option>
<option value="european red squirrel">European red squirrel</option>
<option value="european shelduck">European shelduck</option>
<option value="european spoonbill">European spoonbill</option>
<option value="european stork">European stork</option>
<option value="european wild cat">European wild cat</option>
<option value="fairy penguin">Fairy penguin</option>
<option value="falcon, peregrine">Falcon, peregrine</option>
<option value="falcon, prairie">Falcon, prairie</option>
<option value="fat-tailed dunnart">Fat-tailed dunnart</option>
<option value="feathertail glider">Feathertail glider</option>
<option value="feral rock pigeon">Feral rock pigeon</option>
<option value="ferret, black-footed">Ferret, black-footed</option>
<option value="ferruginous hawk">Ferruginous hawk</option>
<option value="field flicker">Field flicker</option>
<option value="finch, common melba">Finch, common melba</option>
<option value="fisher">Fisher</option>
<option value="flamingo, chilean">Flamingo, chilean</option>
<option value="flamingo, greater">Flamingo, greater</option>
<option value="flamingo, lesser">Flamingo, lesser</option>
<option value="flamingo, roseat">Flamingo, roseat</option>
<option value="flicker, campo">Flicker, campo</option>
<option value="flicker, field">Flicker, field</option>
<option value="flightless cormorant">Flightless cormorant</option>
<option value="flycatcher, tyrant">Flycatcher, tyrant</option>
<option value="flying fox (unidentified)">Flying fox (unidentified)</option>
<option value="fork-tailed drongo">Fork-tailed drongo</option>
<option value="four-horned antelope">Four-horned antelope</option>
<option value="four-spotted skimmer">Four-spotted skimmer</option>
<option value="four-striped grass mouse">Four-striped grass mouse</option>
<option value="fowl, helmeted guinea">Fowl, helmeted guinea</option>
<option value="fox, arctic">Fox, arctic</option>
<option value="fox, asian red">Fox, asian red</option>
<option value="fox, bat-eared">Fox, bat-eared</option>
<option value="fox, blue">Fox, blue</option>
<option value="fox, cape">Fox, cape</option>
<option value="fox, crab-eating">Fox, crab-eating</option>
<option value="fox, grey">Fox, grey</option>
<option value="fox, north american red">Fox, north american red</option>
<option value="fox, pampa gray">Fox, pampa gray</option>
<option value="fox, savanna">Fox, savanna</option>
<option value="fox, silver-backed">Fox, silver-backed</option>
<option value="francolin, coqui">Francolin, coqui</option>
<option value="francolin, swainson's">Francolin, swainson's</option>
<option value="frilled dragon">Frilled dragon</option>
<option value="frilled lizard">Frilled lizard</option>
<option value="fringe-eared oryx">Fringe-eared oryx</option>
<option value="frog (unidentified)">Frog (unidentified)</option>
<option value="frogmouth, tawny">Frogmouth, tawny</option>
<option value="galah">Galah</option>
<option value="galapagos albatross">Galapagos albatross</option>
<option value="galapagos dove">Galapagos dove</option>
<option value="galapagos hawk">Galapagos hawk</option>
<option value="galapagos mockingbird">Galapagos mockingbird</option>
<option value="galapagos penguin">Galapagos penguin</option>
<option value="galapagos sea lion">Galapagos sea lion</option>
<option value="galapagos tortoise">Galapagos tortoise</option>
<option value="gambel's quail">Gambel's quail</option>
<option value="gaur">Gaur</option>
<option value="gazelle, grant's">Gazelle, grant's</option>
<option value="gazelle, thomson's">Gazelle, thomson's</option>
<option value="gazer, sun">Gazer, sun</option>
<option value="gecko (unidentified)">Gecko (unidentified)</option>
<option value="gecko, barking">Gecko, barking</option>
<option value="gecko, bent-toed">Gecko, bent-toed</option>
<option value="gecko, ring-tailed">Gecko, ring-tailed</option>
<option value="gecko, tokay">Gecko, tokay</option>
<option value="gelada baboon">Gelada baboon</option>
<option value="gemsbok">Gemsbok</option>
<option value="genet, common">Genet, common</option>
<option value="genet, small-spotted">Genet, small-spotted</option>
<option value="genoveva">Genoveva</option>
<option value="gerbil (unidentified)">Gerbil (unidentified)</option>
<option value="gerenuk">Gerenuk</option>
<option value="giant anteater">Giant anteater</option>
<option value="giant armadillo">Giant armadillo</option>
<option value="giant girdled lizard">Giant girdled lizard</option>
<option value="giant heron">Giant heron</option>
<option value="giant otter">Giant otter</option>
<option value="gila monster">Gila monster</option>
<option value="giraffe">Giraffe</option>
<option value="glider, feathertail">Glider, feathertail</option>
<option value="glider, squirrel">Glider, squirrel</option>
<option value="glider, sugar">Glider, sugar</option>
<option value="glossy ibis">Glossy ibis</option>
<option value="glossy starling (unidentified)">Glossy starling (unidentified)</option>
<option value="gnu, brindled">Gnu, brindled</option>
<option value="goanna lizard">Goanna lizard</option>
<option value="goat, mountain">Goat, mountain</option>
<option value="godwit, hudsonian">Godwit, hudsonian</option>
<option value="golden brush-tailed possum">Golden brush-tailed possum</option>
<option value="golden eagle">Golden eagle</option>
<option value="golden jackal">Golden jackal</option>
<option value="golden-mantled ground squirrel">Golden-mantled ground squirrel</option>
<option value="goldeneye, barrows">Goldeneye, barrows</option>
<option value="goldeneye, common">Goldeneye, common</option>
<option value="goliath heron">Goliath heron</option>
<option value="gonolek, burchell's">Gonolek, burchell's</option>
<option value="goose, andean">Goose, andean</option>
<option value="goose, canada">Goose, canada</option>
<option value="goose, cape barren">Goose, cape barren</option>
<option value="goose, cereopsis">Goose, cereopsis</option>
<option value="goose, egyptian">Goose, egyptian</option>
<option value="goose, greylag">Goose, greylag</option>
<option value="goose, knob-nosed">Goose, knob-nosed</option>
<option value="goose, snow">Goose, snow</option>
<option value="goose, spur-winged">Goose, spur-winged</option>
<option value="gorilla, western lowland">Gorilla, western lowland</option>
<option value="grant's gazelle">Grant's gazelle</option>
<option value="gray duiker">Gray duiker</option>
<option value="gray heron">Gray heron</option>
<option value="gray langur">Gray langur</option>
<option value="gray rhea">Gray rhea</option>
<option value="great cormorant">Great cormorant</option>
<option value="great egret">Great egret</option>
<option value="great horned owl">Great horned owl</option>
<option value="great kiskadee">Great kiskadee</option>
<option value="great skua">Great skua</option>
<option value="great white pelican">Great white pelican</option>
<option value="greater adjutant stork">Greater adjutant stork</option>
<option value="greater blue-eared starling">Greater blue-eared starling</option>
<option value="greater flamingo">Greater flamingo</option>
<option value="greater kudu">Greater kudu</option>
<option value="greater rhea">Greater rhea</option>
<option value="greater roadrunner">Greater roadrunner</option>
<option value="greater sage grouse">Greater sage grouse</option>
<option value="grebe, little">Grebe, little</option>
<option value="green heron">Green heron</option>
<option value="green vine snake">Green vine snake</option>
<option value="green-backed heron">Green-backed heron</option>
<option value="green-winged macaw">Green-winged macaw</option>
<option value="green-winged trumpeter">Green-winged trumpeter</option>
<option value="grenadier, common">Grenadier, common</option>
<option value="grenadier, purple">Grenadier, purple</option>
<option value="grey fox">Grey fox</option>
<option value="grey heron">Grey heron</option>
<option value="grey lourie">Grey lourie</option>
<option value="grey mouse lemur">Grey mouse lemur</option>
<option value="grey phalarope">Grey phalarope</option>
<option value="grey-footed squirrel">Grey-footed squirrel</option>
<option value="greylag goose">Greylag goose</option>
<option value="griffon vulture">Griffon vulture</option>
<option value="grison">Grison</option>
<option value="grizzly bear">Grizzly bear</option>
<option value="ground legaan">Ground legaan</option>
<option value="ground monitor (unidentified)">Ground monitor (unidentified)</option>
<option value="groundhog">Groundhog</option>
<option value="grouse, greater sage">Grouse, greater sage</option>
<option value="grouse, sage">Grouse, sage</option>
<option value="guanaco">Guanaco</option>
<option value="guerza">Guerza</option>
<option value="gull, dusky">Gull, dusky</option>
<option value="gull, herring">Gull, herring</option>
<option value="gull, kelp">Gull, kelp</option>
<option value="gull, lava">Gull, lava</option>
<option value="gull, pacific">Gull, pacific</option>
<option value="gull, silver">Gull, silver</option>
<option value="gull, southern black-backed">Gull, southern black-backed</option>
<option value="gull, swallow-tail">Gull, swallow-tail</option>
<option value="gulls (unidentified)">Gulls (unidentified)</option>
<option value="hanuman langur">Hanuman langur</option>
<option value="harbor seal">Harbor seal</option>
<option value="hare, arctic">Hare, arctic</option>
<option value="hartebeest, coke's">Hartebeest, coke's</option>
<option value="hartebeest, red">Hartebeest, red</option>
<option value="hawk, ferruginous">Hawk, ferruginous</option>
<option value="hawk, galapagos">Hawk, galapagos</option>
<option value="hawk, red-tailed">Hawk, red-tailed</option>
<option value="hawk-eagle, crowned">Hawk-eagle, crowned</option>
<option value="hawk-headed parrot">Hawk-headed parrot</option>
<option value="hedgehog, south african">Hedgehog, south african</option>
<option value="helmeted guinea fowl">Helmeted guinea fowl</option>
<option value="hen, sage">Hen, sage</option>
<option value="heron, black-crowned night">Heron, black-crowned night</option>
<option value="heron, boat-billed">Heron, boat-billed</option>
<option value="heron, giant">Heron, giant</option>
<option value="heron, goliath">Heron, goliath</option>
<option value="heron, gray">Heron, gray</option>
<option value="heron, green">Heron, green</option>
<option value="heron, green-backed">Heron, green-backed</option>
<option value="heron, grey">Heron, grey</option>
<option value="heron, little">Heron, little</option>
<option value="heron, striated">Heron, striated</option>
<option value="heron, yellow-crowned night">Heron, yellow-crowned night</option>
<option value="herring gull">Herring gull</option>
<option value="hippopotamus">Hippopotamus</option>
<option value="hoary marmot">Hoary marmot</option>
<option value="hoffman's sloth">Hoffman's sloth</option>
<option value="honey badger">Honey badger</option>
<option value="hoopoe, eurasian">Hoopoe, eurasian</option>
<option value="hornbill, leadbeateri's ground">Hornbill, leadbeateri's ground</option>
<option value="hornbill, red-billed">Hornbill, red-billed</option>
<option value="hornbill, southern ground">Hornbill, southern ground</option>
<option value="hornbill, yellow-billed">Hornbill, yellow-billed</option>
<option value="horned lark">Horned lark</option>
<option value="horned puffin">Horned puffin</option>
<option value="horned rattlesnake">Horned rattlesnake</option>
<option value="hottentot teal">Hottentot teal</option>
<option value="house crow">House crow</option>
<option value="house sparrow">House sparrow</option>
<option value="hudsonian godwit">Hudsonian godwit</option>
<option value="hummingbird (unidentified)">Hummingbird (unidentified)</option>
<option value="huron">Huron</option>
<option value="hyena, brown">Hyena, brown</option>
<option value="hyena, spotted">Hyena, spotted</option>
<option value="hyena, striped">Hyena, striped</option>
<option value="hyrax">Hyrax</option>
<option value="ibex">Ibex</option>
<option value="ibis, glossy">Ibis, glossy</option>
<option value="ibis, puna">Ibis, puna</option>
<option value="ibis, sacred">Ibis, sacred</option>
<option value="iguana, common green">Iguana, common green</option>
<option value="iguana, land">Iguana, land</option>
<option value="iguana, marine">Iguana, marine</option>
<option value="impala">Impala</option>
<option value="indian giant squirrel">Indian giant squirrel</option>
<option value="indian jackal">Indian jackal</option>
<option value="indian leopard">Indian leopard</option>
<option value="indian mynah">Indian mynah</option>
<option value="indian peacock">Indian peacock</option>
<option value="indian porcupine">Indian porcupine</option>
<option value="indian red admiral">Indian red admiral</option>
<option value="indian star tortoise">Indian star tortoise</option>
<option value="indian tree pie">Indian tree pie</option>
<option value="insect, stick">Insect, stick</option>
<option value="jabiru stork">Jabiru stork</option>
<option value="jacana, african">Jacana, african</option>
<option value="jackal, asiatic">Jackal, asiatic</option>
<option value="jackal, black-backed">Jackal, black-backed</option>
<option value="jackal, golden">Jackal, golden</option>
<option value="jackal, indian">Jackal, indian</option>
<option value="jackal, silver-backed">Jackal, silver-backed</option>
<option value="jackrabbit, white-tailed">Jackrabbit, white-tailed</option>
<option value="jaeger, long-tailed">Jaeger, long-tailed</option>
<option value="jaguar">Jaguar</option>
<option value="jaguarundi">Jaguarundi</option>
<option value="japanese macaque">Japanese macaque</option>
<option value="javan gold-spotted mongoose">Javan gold-spotted mongoose</option>
<option value="javanese cormorant">Javanese cormorant</option>
<option value="jungle cat">Jungle cat</option>
<option value="jungle kangaroo">Jungle kangaroo</option>
<option value="kaffir cat">Kaffir cat</option>
<option value="kafue flats lechwe">Kafue flats lechwe</option>
<option value="kalahari scrub robin">Kalahari scrub robin</option>
<option value="kangaroo, black-faced">Kangaroo, black-faced</option>
<option value="kangaroo, brush-tailed rat">Kangaroo, brush-tailed rat</option>
<option value="kangaroo, eastern grey">Kangaroo, eastern grey</option>
<option value="kangaroo, jungle">Kangaroo, jungle</option>
<option value="kangaroo, red">Kangaroo, red</option>
<option value="kangaroo, western grey">Kangaroo, western grey</option>
<option value="kelp gull">Kelp gull</option>
<option value="killer whale">Killer whale</option>
<option value="king cormorant">King cormorant</option>
<option value="king vulture">King vulture</option>
<option value="kingfisher, malachite">Kingfisher, malachite</option>
<option value="kingfisher, pied">Kingfisher, pied</option>
<option value="kingfisher, white-throated">Kingfisher, white-throated</option>
<option value="kinkajou">Kinkajou</option>
<option value="kirk's dik dik">Kirk's dik dik</option>
<option value="kiskadee, great">Kiskadee, great</option>
<option value="kite, black">Kite, black</option>
<option value="klipspringer">Klipspringer</option>
<option value="knob-nosed goose">Knob-nosed goose</option>
<option value="koala">Koala</option>
<option value="komodo dragon">Komodo dragon</option>
<option value="kongoni">Kongoni</option>
<option value="kookaburra, laughing">Kookaburra, laughing</option>
<option value="kori bustard">Kori bustard</option>
<option value="kudu, greater">Kudu, greater</option>
<option value="land iguana">Land iguana</option>
<option value="langur, common">Langur, common</option>
<option value="langur, gray">Langur, gray</option>
<option value="langur, hanuman">Langur, hanuman</option>
<option value="lappet-faced vulture">Lappet-faced vulture</option>
<option value="lapwing (unidentified)">Lapwing (unidentified)</option>
<option value="lapwing, southern">Lapwing, southern</option>
<option value="large cormorant">Large cormorant</option>
<option value="large-eared bushbaby">Large-eared bushbaby</option>
<option value="lark, horned">Lark, horned</option>
<option value="laughing dove">Laughing dove</option>
<option value="laughing kookaburra">Laughing kookaburra</option>
<option value="lava gull">Lava gull</option>
<option value="leadbeateri's ground hornbill">Leadbeateri's ground hornbill</option>
<option value="least chipmunk">Least chipmunk</option>
<option value="lechwe, kafue flats">Lechwe, kafue flats</option>
<option value="legaan, monitor (unidentified)">Legaan, Monitor (unidentified)</option>
<option value="legaan, ground">Legaan, ground</option>
<option value="legaan, water">Legaan, water</option>
<option value="lemming, arctic">Lemming, arctic</option>
<option value="lemming, collared">Lemming, collared</option>
<option value="lemur, brown">Lemur, brown</option>
<option value="lemur, grey mouse">Lemur, grey mouse</option>
<option value="lemur, lesser mouse">Lemur, lesser mouse</option>
<option value="lemur, ring-tailed">Lemur, ring-tailed</option>
<option value="lemur, sportive">Lemur, sportive</option>
<option value="leopard">Leopard</option>
<option value="leopard, indian">Leopard, indian</option>
<option value="lesser double-collared sunbird">Lesser double-collared sunbird</option>
<option value="lesser flamingo">Lesser flamingo</option>
<option value="lesser masked weaver">Lesser masked weaver</option>
<option value="lesser mouse lemur">Lesser mouse lemur</option>
<option value="levaillant's barbet">Levaillant's barbet</option>
<option value="lilac-breasted roller">Lilac-breasted roller</option>
<option value="lily trotter">Lily trotter</option>
<option value="lion, african">Lion, african</option>
<option value="lion, asian">Lion, asian</option>
<option value="lion, australian sea">Lion, australian sea</option>
<option value="lion, california sea">Lion, california sea</option>
<option value="lion, galapagos sea">Lion, galapagos sea</option>
<option value="lion, mountain">Lion, mountain</option>
<option value="lion, south american sea">Lion, south american sea</option>
<option value="lion, southern sea">Lion, southern sea</option>
<option value="lion, steller sea">Lion, steller sea</option>
<option value="lion, steller's sea">Lion, steller's sea</option>
<option value="little blue penguin">Little blue penguin</option>
<option value="little brown bat">Little brown bat</option>
<option value="little brown dove">Little brown dove</option>
<option value="little cormorant">Little cormorant</option>
<option value="little grebe">Little grebe</option>
<option value="little heron">Little heron</option>
<option value="lizard (unidentified)">Lizard (unidentified)</option>
<option value="lizard, blue-tongued">Lizard, blue-tongued</option>
<option value="lizard, collared">Lizard, collared</option>
<option value="lizard, desert spiny">Lizard, desert spiny</option>
<option value="lizard, frilled">Lizard, frilled</option>
<option value="lizard, giant girdled">Lizard, giant girdled</option>
<option value="lizard, goanna">Lizard, goanna</option>
<option value="lizard, mexican beaded">Lizard, mexican beaded</option>
<option value="llama">Llama</option>
<option value="long-billed cockatoo">Long-billed cockatoo</option>
<option value="long-billed corella">Long-billed corella</option>
<option value="long-crested hawk eagle">Long-crested hawk eagle</option>
<option value="long-finned pilot whale">Long-finned pilot whale</option>
<option value="long-necked turtle">Long-necked turtle</option>
<option value="long-nosed bandicoot">Long-nosed bandicoot</option>
<option value="long-tailed jaeger">Long-tailed jaeger</option>
<option value="long-tailed skua">Long-tailed skua</option>
<option value="long-tailed spotted cat">Long-tailed spotted cat</option>
<option value="lorikeet, scaly-breasted">Lorikeet, scaly-breasted</option>
<option value="loris, slender">Loris, slender</option>
<option value="lory, rainbow">Lory, rainbow</option>
<option value="lourie, grey">Lourie, grey</option>
<option value="lynx, african">Lynx, african</option>
<option value="macaque, bonnet">Macaque, bonnet</option>
<option value="macaque, japanese">Macaque, japanese</option>
<option value="macaque, pig-tailed">Macaque, pig-tailed</option>
<option value="macaque, rhesus">Macaque, rhesus</option>
<option value="macaw, blue and gold">Macaw, blue and gold</option>
<option value="macaw, blue and yellow">Macaw, blue and yellow</option>
<option value="macaw, green-winged">Macaw, green-winged</option>
<option value="macaw, red and blue">Macaw, red and blue</option>
<option value="macaw, scarlet">Macaw, scarlet</option>
<option value="madagascar fruit bat">Madagascar fruit bat</option>
<option value="madagascar hawk owl">Madagascar hawk owl</option>
<option value="magellanic penguin">Magellanic penguin</option>
<option value="magistrate black colobus">Magistrate black colobus</option>
<option value="magnificent frigate bird">Magnificent frigate bird</option>
<option value="magpie, australian">Magpie, australian</option>
<option value="magpie, black-backed">Magpie, black-backed</option>
<option value="malabar squirrel">Malabar squirrel</option>
<option value="malachite kingfisher">Malachite kingfisher</option>
<option value="malagasy ground boa">Malagasy ground boa</option>
<option value="malay squirrel (unidentified)">Malay squirrel (unidentified)</option>
<option value="mallard">Mallard</option>
<option value="malleefowl">Malleefowl</option>
<option value="manatee">Manatee</option>
<option value="mandras tree shrew">Mandras tree shrew</option>
<option value="mara">Mara</option>
<option value="marabou stork">Marabou stork</option>
<option value="margay">Margay</option>
<option value="marine iguana">Marine iguana</option>
<option value="marmot, hoary">Marmot, hoary</option>
<option value="marmot, yellow-bellied">Marmot, yellow-bellied</option>
<option value="marshbird, brown and yellow">Marshbird, brown and yellow</option>
<option value="marten, american">Marten, american</option>
<option value="masked booby">Masked booby</option>
<option value="meerkat">Meerkat</option>
<option value="meerkat, red">Meerkat, red</option>
<option value="mexican beaded lizard">Mexican beaded lizard</option>
<option value="mexican boa">Mexican boa</option>
<option value="mexican wolf">Mexican wolf</option>
<option value="miner's cat">Miner's cat</option>
<option value="mississippi alligator">Mississippi alligator</option>
<option value="moccasin, water">Moccasin, water</option>
<option value="mocking cliffchat">Mocking cliffchat</option>
<option value="mockingbird, galapagos">Mockingbird, galapagos</option>
<option value="mongoose, banded">Mongoose, banded</option>
<option value="mongoose, eastern dwarf">Mongoose, eastern dwarf</option>
<option value="mongoose, javan gold-spotted">Mongoose, javan gold-spotted</option>
<option value="mongoose, small indian">Mongoose, small indian</option>
<option value="mongoose, yellow">Mongoose, yellow</option>
<option value="monitor lizard (unidentified)">Monitor lizard (unidentified)</option>
<option value="monitor, two-banded">Monitor, two-banded</option>
<option value="monitor, water">Monitor, water</option>
<option value="monitor, white-throated">Monitor, white-throated</option>
<option value="monkey, black spider">Monkey, black spider</option>
<option value="monkey, bleeding heart">Monkey, bleeding heart</option>
<option value="monkey, red howler">Monkey, red howler</option>
<option value="monkey, rhesus">Monkey, rhesus</option>
<option value="monkey, vervet">Monkey, vervet</option>
<option value="monster, gila">Monster, gila</option>
<option value="moorhen, purple">Moorhen, purple</option>
<option value="moose">Moose</option>
<option value="mouflon">Mouflon</option>
<option value="mountain duck">Mountain duck</option>
<option value="mountain goat">Mountain goat</option>
<option value="mountain lion">Mountain lion</option>
<option value="mourning collared dove">Mourning collared dove</option>
<option value="mouse, four-striped grass">Mouse, four-striped grass</option>
<option value="mudskipper (unidentified)">Mudskipper (unidentified)</option>
<option value="mule deer">Mule deer</option>
<option value="musk ox">Musk ox</option>
<option value="mynah, common">Mynah, common</option>
<option value="mynah, indian">Mynah, indian</option>
<option value="native cat">Native cat</option>
<option value="nelson ground squirrel">Nelson ground squirrel</option>
<option value="neotropic cormorant">Neotropic cormorant</option>
<option value="netted rock dragon">Netted rock dragon</option>
<option value="nighthawk, common">Nighthawk, common</option>
<option value="nile crocodile">Nile crocodile</option>
<option value="nilgai">Nilgai</option>
<option value="nine-banded armadillo">Nine-banded armadillo</option>
<option value="north american beaver">North American beaver</option>
<option value="north american porcupine">North American porcupine</option>
<option value="north american red fox">North American red fox</option>
<option value="north american river otter">North American river otter</option>
<option value="northern elephant seal">Northern elephant seal</option>
<option value="northern fur seal">Northern fur seal</option>
<option value="northern phalarope">Northern phalarope</option>
<option value="nubian bee-eater">Nubian bee-eater</option>
<option value="numbat">Numbat</option>
<option value="nutcracker, clark's">Nutcracker, clark's</option>
<option value="nuthatch, red-breasted">Nuthatch, red-breasted</option>
<option value="nyala">Nyala</option>
<option value="ocelot">Ocelot</option>
<option value="old world fruit bat (unidentified)">Old world fruit bat (unidentified)</option>
<option value="olive baboon">Olive baboon</option>
<option value="onager">Onager</option>
<option value="openbill stork">Openbill stork</option>
<option value="openbill, asian">Openbill, asian</option>
<option value="opossum, american virginia">Opossum, american virginia</option>
<option value="orca">Orca</option>
<option value="oribi">Oribi</option>
<option value="oriental short-clawed otter">Oriental short-clawed otter</option>
<option value="oriental white-backed vulture">Oriental white-backed vulture</option>
<option value="ornate rock dragon">Ornate rock dragon</option>
<option value="oryx, beisa">Oryx, beisa</option>
<option value="oryx, fringe-eared">Oryx, fringe-eared</option>
<option value="osprey">Osprey</option>
<option value="ostrich">Ostrich</option>
<option value="otter, african clawless">Otter, african clawless</option>
<option value="otter, brazilian">Otter, brazilian</option>
<option value="otter, canadian river">Otter, canadian river</option>
<option value="otter, cape clawless">Otter, cape clawless</option>
<option value="otter, giant">Otter, giant</option>
<option value="otter, north american river">Otter, north american river</option>
<option value="otter, oriental short-clawed">Otter, oriental short-clawed</option>
<option value="otter, small-clawed">Otter, small-clawed</option>
<option value="ovenbird">Ovenbird</option>
<option value="owl, australian masked">Owl, australian masked</option>
<option value="owl, burrowing">Owl, burrowing</option>
<option value="owl, great horned">Owl, great horned</option>
<option value="owl, madagascar hawk">Owl, madagascar hawk</option>
<option value="owl, snowy">Owl, snowy</option>
<option value="owl, white-browed">Owl, white-browed</option>
<option value="ox, musk">Ox, musk</option>
<option value="oystercatcher, blackish">Oystercatcher, blackish</option>
<option value="paca">Paca</option>
<option value="pacific gull">Pacific gull</option>
<option value="paddy heron (unidentified)">Paddy heron (unidentified)</option>
<option value="pademelon, red-legged">Pademelon, red-legged</option>
<option value="painted stork">Painted stork</option>
<option value="pale white-eye">Pale white-eye</option>
<option value="pale-throated three-toed sloth">Pale-throated three-toed sloth</option>
<option value="pallas's fish eagle">Pallas's fish eagle</option>
<option value="palm squirrel">Palm squirrel</option>
<option value="pampa gray fox">Pampa gray fox</option>
<option value="paradoxure">Paradoxure</option>
<option value="parakeet, rose-ringed">Parakeet, rose-ringed</option>
<option value="parrot, hawk-headed">Parrot, hawk-headed</option>
<option value="partridge, coqui">Partridge, coqui</option>
<option value="peacock, blue">Peacock, blue</option>
<option value="peacock, indian">Peacock, indian</option>
<option value="peccary, collared">Peccary, collared</option>
<option value="peccary, white-lipped">Peccary, white-lipped</option>
<option value="pelican, australian">Pelican, australian</option>
<option value="pelican, brown">Pelican, brown</option>
<option value="pelican, eastern white">Pelican, eastern white</option>
<option value="pelican, great white">Pelican, great white</option>
<option value="penguin, fairy">Penguin, fairy</option>
<option value="penguin, galapagos">Penguin, galapagos</option>
<option value="penguin, little blue">Penguin, little blue</option>
<option value="penguin, magellanic">Penguin, magellanic</option>
<option value="peregrine falcon">Peregrine falcon</option>
<option value="phalarope, grey">Phalarope, grey</option>
<option value="phalarope, northern">Phalarope, northern</option>
<option value="phalarope, red">Phalarope, red</option>
<option value="phalarope, red-necked">Phalarope, red-necked</option>
<option value="phascogale, brush-tailed">Phascogale, brush-tailed</option>
<option value="phascogale, red-tailed">Phascogale, red-tailed</option>
<option value="pheasant, common">Pheasant, common</option>
<option value="pheasant, ring-necked">Pheasant, ring-necked</option>
<option value="pie, indian tree">Pie, indian tree</option>
<option value="pie, rufous tree">Pie, rufous tree</option>
<option value="pied avocet">Pied avocet</option>
<option value="pied butcher bird">Pied butcher bird</option>
<option value="pied cormorant">Pied cormorant</option>
<option value="pied crow">Pied crow</option>
<option value="pied kingfisher">Pied kingfisher</option>
<option value="pig-tailed macaque">Pig-tailed macaque</option>
<option value="pigeon, feral rock">Pigeon, feral rock</option>
<option value="pigeon, wood">Pigeon, wood</option>
<option value="pine siskin">Pine siskin</option>
<option value="pine snake (unidentified)">Pine snake (unidentified)</option>
<option value="pine squirrel">Pine squirrel</option>
<option value="pintail, bahama">Pintail, bahama</option>
<option value="pintail, white-cheeked">Pintail, white-cheeked</option>
<option value="plains zebra">Plains zebra</option>
<option value="platypus">Platypus</option>
<option value="plover, blacksmith">Plover, blacksmith</option>
<option value="plover, three-banded">Plover, three-banded</option>
<option value="pocket gopher (unidentified)">Pocket gopher (unidentified)</option>
<option value="polar bear">Polar bear</option>
<option value="polecat, african">Polecat, african</option>
<option value="porcupine, african">Porcupine, african</option>
<option value="porcupine, crested">Porcupine, crested</option>
<option value="porcupine, indian">Porcupine, indian</option>
<option value="porcupine, north american">Porcupine, north american</option>
<option value="porcupine, prehensile-tailed">Porcupine, prehensile-tailed</option>
<option value="porcupine, tree">Porcupine, tree</option>
<option value="possum, common brushtail">Possum, common brushtail</option>
<option value="possum, golden brush-tailed">Possum, golden brush-tailed</option>
<option value="possum, pygmy">Possum, pygmy</option>
<option value="possum, ring-tailed">Possum, ring-tailed</option>
<option value="possum, western pygmy">Possum, western pygmy</option>
<option value="potoroo">Potoroo</option>
<option value="prairie falcon">Prairie falcon</option>
<option value="praying mantis (unidentified)">Praying mantis (unidentified)</option>
<option value="prehensile-tailed porcupine">Prehensile-tailed porcupine</option>
<option value="pronghorn">Pronghorn</option>
<option value="puffin, horned">Puffin, horned</option>
<option value="puku">Puku</option>
<option value="puma">Puma</option>
<option value="puma, south american">Puma, south american</option>
<option value="puna ibis">Puna ibis</option>
<option value="purple grenadier">Purple grenadier</option>
<option value="purple moorhen">Purple moorhen</option>
<option value="pygmy possum">Pygmy possum</option>
<option value="python (unidentified)">Python (unidentified)</option>
<option value="python, carpet">Python, carpet</option>
<option value="quail, gambel's">Quail, gambel's</option>
<option value="quoll, eastern">Quoll, eastern</option>
<option value="quoll, spotted-tailed">Quoll, spotted-tailed</option>
<option value="rabbit, eastern cottontail">Rabbit, eastern cottontail</option>
<option value="raccoon dog">Raccoon dog</option>
<option value="raccoon, common">Raccoon, common</option>
<option value="raccoon, crab-eating">Raccoon, crab-eating</option>
<option value="racer snake">Racer snake</option>
<option value="racer, american">Racer, american</option>
<option value="racer, blue">Racer, blue</option>
<option value="radiated tortoise">Radiated tortoise</option>
<option value="rainbow lory">Rainbow lory</option>
<option value="rat, arboral spiny">Rat, arboral spiny</option>
<option value="rat, desert kangaroo">Rat, desert kangaroo</option>
<option value="rat, white-faced tree">Rat, white-faced tree</option>
<option value="rattlesnake, dusky">Rattlesnake, dusky</option>
<option value="rattlesnake, eastern diamondback">Rattlesnake, eastern diamondback</option>
<option value="rattlesnake, horned">Rattlesnake, horned</option>
<option value="raven, cape">Raven, cape</option>
<option value="raven, white-necked">Raven, white-necked</option>
<option value="red and blue macaw">Red and blue macaw</option>
<option value="red brocket">Red brocket</option>
<option value="red deer">Red deer</option>
<option value="red hartebeest">Red hartebeest</option>
<option value="red howler monkey">Red howler monkey</option>
<option value="red kangaroo">Red kangaroo</option>
<option value="red lava crab">Red lava crab</option>
<option value="red meerkat">Red meerkat</option>
<option value="red phalarope">Red phalarope</option>
<option value="red sheep">Red sheep</option>
<option value="red squirrel">Red squirrel</option>
<option value="red-billed buffalo weaver">Red-billed buffalo weaver</option>
<option value="red-billed hornbill">Red-billed hornbill</option>
<option value="red-billed toucan">Red-billed toucan</option>
<option value="red-billed tropic bird">Red-billed tropic bird</option>
<option value="red-breasted cockatoo">Red-breasted cockatoo</option>
<option value="red-breasted nuthatch">Red-breasted nuthatch</option>
<option value="red-capped cardinal">Red-capped cardinal</option>
<option value="red-cheeked cordon bleu">Red-cheeked cordon bleu</option>
<option value="red-headed woodpecker">Red-headed woodpecker</option>
<option value="red-knobbed coot">Red-knobbed coot</option>
<option value="red-legged pademelon">Red-legged pademelon</option>
<option value="red-necked phalarope">Red-necked phalarope</option>
<option value="red-necked wallaby">Red-necked wallaby</option>
<option value="red-shouldered glossy starling">Red-shouldered glossy starling</option>
<option value="red-tailed cockatoo">Red-tailed cockatoo</option>
<option value="red-tailed hawk">Red-tailed hawk</option>
<option value="red-tailed phascogale">Red-tailed phascogale</option>
<option value="red-tailed wambenger">Red-tailed wambenger</option>
<option value="red-winged blackbird">Red-winged blackbird</option>
<option value="red-winged hawk (unidentified)">Red-winged hawk (unidentified)</option>
<option value="reedbuck, bohor">Reedbuck, bohor</option>
<option value="reindeer">Reindeer</option>
<option value="rhea, common">Rhea, common</option>
<option value="rhea, gray">Rhea, gray</option>
<option value="rhea, greater">Rhea, greater</option>
<option value="rhesus macaque">Rhesus macaque</option>
<option value="rhesus monkey">Rhesus monkey</option>
<option value="rhinoceros, black">Rhinoceros, black</option>
<option value="rhinoceros, square-lipped">Rhinoceros, square-lipped</option>
<option value="rhinoceros, white">Rhinoceros, white</option>
<option value="richardson's ground squirrel">Richardson's ground squirrel</option>
<option value="ring dove">Ring dove</option>
<option value="ring-necked pheasant">Ring-necked pheasant</option>
<option value="ring-tailed coatimundi">Ring-tailed coatimundi</option>
<option value="ring-tailed gecko">Ring-tailed gecko</option>
<option value="ring-tailed lemur">Ring-tailed lemur</option>
<option value="ring-tailed possum">Ring-tailed possum</option>
<option value="ringtail">Ringtail</option>
<option value="ringtail cat">Ringtail cat</option>
<option value="ringtail, common">Ringtail, common</option>
<option value="river wallaby">River wallaby</option>
<option value="roadrunner, greater">Roadrunner, greater</option>
<option value="roan antelope">Roan antelope</option>
<option value="robin, kalahari scrub">Robin, kalahari scrub</option>
<option value="robin, white-throated">Robin, white-throated</option>
<option value="rock dove">Rock dove</option>
<option value="roe deer">Roe deer</option>
<option value="roller, lilac-breasted">Roller, lilac-breasted</option>
<option value="rose-ringed parakeet">Rose-ringed parakeet</option>
<option value="roseat flamingo">Roseat flamingo</option>
<option value="roseate cockatoo">Roseate cockatoo</option>
<option value="royal tern">Royal tern</option>
<option value="rufous tree pie">Rufous tree pie</option>
<option value="rufous-collared sparrow">Rufous-collared sparrow</option>
<option value="russian dragonfly">Russian dragonfly</option>
<option value="sable antelope">Sable antelope</option>
<option value="sacred ibis">Sacred ibis</option>
<option value="saddle-billed stork">Saddle-billed stork</option>
<option value="sage grouse">Sage grouse</option>
<option value="sage hen">Sage hen</option>
<option value="sally lightfoot crab">Sally lightfoot crab</option>
<option value="salmon pink bird eater tarantula">Salmon pink bird eater tarantula</option>
<option value="salmon, sockeye">Salmon, sockeye</option>
<option value="sambar">Sambar</option>
<option value="sandgrouse, yellow-throated">Sandgrouse, yellow-throated</option>
<option value="sandhill crane">Sandhill crane</option>
<option value="sandpiper, spotted wood">Sandpiper, spotted wood</option>
<option value="sarus crane">Sarus crane</option>
<option value="savanna baboon">Savanna baboon</option>
<option value="savanna fox">Savanna fox</option>
<option value="savannah deer">Savannah deer</option>
<option value="savannah deer (unidentified)">Savannah deer (unidentified)</option>
<option value="scaly-breasted lorikeet">Scaly-breasted lorikeet</option>
<option value="scarlet macaw">Scarlet macaw</option>
<option value="scottish highland cow">Scottish highland cow</option>
<option value="screamer, crested">Screamer, crested</option>
<option value="screamer, southern">Screamer, southern</option>
<option value="sea birds (unidentified)">Sea birds (unidentified)</option>
<option value="seal, common">Seal, common</option>
<option value="seal, harbor">Seal, harbor</option>
<option value="seal, northern elephant">Seal, northern elephant</option>
<option value="seal, northern fur">Seal, northern fur</option>
<option value="seal, southern elephant">Seal, southern elephant</option>
<option value="secretary bird">Secretary bird</option>
<option value="serval">Serval</option>
<option value="seven-banded armadillo">Seven-banded armadillo</option>
<option value="shark, blue">Shark, blue</option>
<option value="sheathbill, snowy">Sheathbill, snowy</option>
<option value="sheep, american bighorn">Sheep, american bighorn</option>
<option value="sheep, red">Sheep, red</option>
<option value="sheep, stone">Sheep, stone</option>
<option value="shelduck, common">Shelduck, common</option>
<option value="shelduck, european">Shelduck, european</option>
<option value="short-beaked echidna">Short-beaked echidna</option>
<option value="short-nosed bandicoot">Short-nosed bandicoot</option>
<option value="shrew, mandras tree">Shrew, mandras tree</option>
<option value="shrike, common boubou">Shrike, common boubou</option>
<option value="shrike, crimson-breasted">Shrike, crimson-breasted</option>
<option value="shrike, southern white-crowned">Shrike, southern white-crowned</option>
<option value="sidewinder">Sidewinder</option>
<option value="sifaka, verreaux's">Sifaka, verreaux's</option>
<option value="silver gull">Silver gull</option>
<option value="silver-backed fox">Silver-backed fox</option>
<option value="silver-backed jackal">Silver-backed jackal</option>
<option value="siskin, pine">Siskin, pine</option>
<option value="siskin, yellow-rumped">Siskin, yellow-rumped</option>
<option value="skimmer, four-spotted">Skimmer, four-spotted</option>
<option value="skink, african">Skink, african</option>
<option value="skink, blue-tongued">Skink, blue-tongued</option>
<option value="skua, great">Skua, great</option>
<option value="skua, long-tailed">Skua, long-tailed</option>
<option value="skunk, striped">Skunk, striped</option>
<option value="skunk, western spotted">Skunk, western spotted</option>
<option value="slender loris">Slender loris</option>
<option value="slender-billed cockatoo">Slender-billed cockatoo</option>
<option value="sloth bear">Sloth bear</option>
<option value="sloth, hoffman's">Sloth, hoffman's</option>
<option value="sloth, pale-throated three-toed">Sloth, pale-throated three-toed</option>
<option value="sloth, two-toed">Sloth, two-toed</option>
<option value="sloth, two-toed tree">Sloth, two-toed tree</option>
<option value="small indian mongoose">Small Indian mongoose</option>
<option value="small-clawed otter">Small-clawed otter</option>
<option value="small-spotted genet">Small-spotted genet</option>
<option value="small-toothed palm civet">Small-toothed palm civet</option>
<option value="smith's bush squirrel">Smith's bush squirrel</option>
<option value="snake (unidentified)">Snake (unidentified)</option>
<option value="snake, buttermilk">Snake, buttermilk</option>
<option value="snake, carpet">Snake, carpet</option>
<option value="snake, eastern indigo">Snake, eastern indigo</option>
<option value="snake, green vine">Snake, green vine</option>
<option value="snake, racer">Snake, racer</option>
<option value="snake, tiger">Snake, tiger</option>
<option value="snake, western patch-nosed">Snake, western patch-nosed</option>
<option value="snake-necked turtle">Snake-necked turtle</option>
<option value="snow goose">Snow goose</option>
<option value="snowy egret">Snowy egret</option>
<option value="snowy owl">Snowy owl</option>
<option value="snowy sheathbill">Snowy sheathbill</option>
<option value="sociable weaver">Sociable weaver</option>
<option value="sockeye salmon">Sockeye salmon</option>
<option value="south african hedgehog">South African hedgehog</option>
<option value="south american meadowlark (unidentified)">South American meadowlark (unidentified)</option>
<option value="south american puma">South American puma</option>
<option value="south american sea lion">South American sea lion</option>
<option value="southern black-backed gull">Southern black-backed gull</option>
<option value="southern boubou">Southern boubou</option>
<option value="southern brown bandicoot">Southern brown bandicoot</option>
<option value="southern elephant seal">Southern elephant seal</option>
<option value="southern ground hornbill">Southern ground hornbill</option>
<option value="southern hairy-nosed wombat">Southern hairy-nosed wombat</option>
<option value="southern lapwing">Southern lapwing</option>
<option value="southern right whale">Southern right whale</option>
<option value="southern screamer">Southern screamer</option>
<option value="southern sea lion">Southern sea lion</option>
<option value="southern tamandua">Southern tamandua</option>
<option value="southern white-crowned shrike">Southern white-crowned shrike</option>
<option value="sparrow, house">Sparrow, house</option>
<option value="sparrow, rufous-collared">Sparrow, rufous-collared</option>
<option value="spectacled caiman">Spectacled caiman</option>
<option value="spider, wolf">Spider, wolf</option>
<option value="spoonbill, european">Spoonbill, european</option>
<option value="spoonbill, white">Spoonbill, white</option>
<option value="sportive lemur">Sportive lemur</option>
<option value="spotted deer">Spotted deer</option>
<option value="spotted hyena">Spotted hyena</option>
<option value="spotted wood sandpiper">Spotted wood sandpiper</option>
<option value="spotted-tailed quoll">Spotted-tailed quoll</option>
<option value="springbok">Springbok</option>
<option value="springbuck">Springbuck</option>
<option value="springhare">Springhare</option>
<option value="spur-winged goose">Spur-winged goose</option>
<option value="spurfowl, yellow-necked">Spurfowl, yellow-necked</option>
<option value="square-lipped rhinoceros">Square-lipped rhinoceros</option>
<option value="squirrel glider">Squirrel glider</option>
<option value="squirrel, african bush">Squirrel, african bush</option>
<option value="squirrel, antelope ground">Squirrel, antelope ground</option>
<option value="squirrel, arctic ground">Squirrel, arctic ground</option>
<option value="squirrel, eastern fox">Squirrel, eastern fox</option>
<option value="squirrel, eurasian red">Squirrel, eurasian red</option>
<option value="squirrel, european red">Squirrel, european red</option>
<option value="squirrel, golden-mantled ground">Squirrel, golden-mantled ground</option>
<option value="squirrel, grey-footed">Squirrel, grey-footed</option>
<option value="squirrel, indian giant">Squirrel, indian giant</option>
<option value="squirrel, malabar">Squirrel, malabar</option>
<option value="squirrel, nelson ground">Squirrel, nelson ground</option>
<option value="squirrel, palm">Squirrel, palm</option>
<option value="squirrel, pine">Squirrel, pine</option>
<option value="squirrel, red">Squirrel, red</option>
<option value="squirrel, richardson's ground">Squirrel, richardson's ground</option>
<option value="squirrel, smith's bush">Squirrel, smith's bush</option>
<option value="squirrel, thirteen-lined">Squirrel, thirteen-lined</option>
<option value="squirrel, uinta ground">Squirrel, uinta ground</option>
<option value="stanley bustard">Stanley bustard</option>
<option value="stanley crane">Stanley crane</option>
<option value="starfish, crown of thorns">Starfish, crown of thorns</option>
<option value="starling, cape">Starling, cape</option>
<option value="starling, greater blue-eared">Starling, greater blue-eared</option>
<option value="starling, red-shouldered glossy">Starling, red-shouldered glossy</option>
<option value="starling, superb">Starling, superb</option>
<option value="steenbok">Steenbok</option>
<option value="steenbuck">Steenbuck</option>
<option value="steller sea lion">Steller sea lion</option>
<option value="steller's sea lion">Steller's sea lion</option>
<option value="stick insect">Stick insect</option>
<option value="stilt, black-winged">Stilt, black-winged</option>
<option value="stone sheep">Stone sheep</option>
<option value="stork, black-necked">Stork, black-necked</option>
<option value="stork, european">Stork, european</option>
<option value="stork, greater adjutant">Stork, greater adjutant</option>
<option value="stork, jabiru">Stork, jabiru</option>
<option value="stork, marabou">Stork, marabou</option>
<option value="stork, openbill">Stork, openbill</option>
<option value="stork, painted">Stork, painted</option>
<option value="stork, saddle-billed">Stork, saddle-billed</option>
<option value="stork, white">Stork, white</option>
<option value="stork, white-necked">Stork, white-necked</option>
<option value="stork, woolly-necked">Stork, woolly-necked</option>
<option value="stork, yellow-billed">Stork, yellow-billed</option>
<option value="striated heron">Striated heron</option>
<option value="striped dolphin">Striped dolphin</option>
<option value="striped hyena">Striped hyena</option>
<option value="striped skunk">Striped skunk</option>
<option value="sugar glider">Sugar glider</option>
<option value="sulfur-crested cockatoo">Sulfur-crested cockatoo</option>
<option value="sun gazer">Sun gazer</option>
<option value="sunbird, lesser double-collared">Sunbird, lesser double-collared</option>
<option value="sungazer, yellow-brown">Sungazer, yellow-brown</option>
<option value="superb starling">Superb starling</option>
<option value="suricate">Suricate</option>
<option value="swainson's francolin">Swainson's francolin</option>
<option value="swallow (unidentified)">Swallow (unidentified)</option>
<option value="swallow-tail gull">Swallow-tail gull</option>
<option value="swamp deer">Swamp deer</option>
<option value="swan, black">Swan, black</option>
<option value="swan, trumpeter">Swan, trumpeter</option>
<option value="tailless tenrec">Tailless tenrec</option>
<option value="tamandua, southern">Tamandua, southern</option>
<option value="tammar wallaby">Tammar wallaby</option>
<option value="tapir, brazilian">Tapir, brazilian</option>
<option value="tarantula">Tarantula</option>
<option value="tarantula, salmon pink bird eater">Tarantula, salmon pink bird eater</option>
<option value="tasmanian devil">Tasmanian devil</option>
<option value="tawny eagle">Tawny eagle</option>
<option value="tawny frogmouth">Tawny frogmouth</option>
<option value="tayra">Tayra</option>
<option value="teal, hottentot">Teal, hottentot</option>
<option value="tenrec, tailless">Tenrec, tailless</option>
<option value="tern, arctic">Tern, arctic</option>
<option value="tern, royal">Tern, royal</option>
<option value="tern, white-winged">Tern, white-winged</option>
<option value="tern, white-winged black">Tern, white-winged black</option>
<option value="thirteen-lined squirrel">Thirteen-lined squirrel</option>
<option value="thomson's gazelle">Thomson's gazelle</option>
<option value="thrasher, curve-billed">Thrasher, curve-billed</option>
<option value="three-banded plover">Three-banded plover</option>
<option value="tiger">Tiger</option>
<option value="tiger cat">Tiger cat</option>
<option value="tiger snake">Tiger snake</option>
<option value="timber wolf">Timber wolf</option>
<option value="tinamou, elegant crested">Tinamou, elegant crested</option>
<option value="toddy cat">Toddy cat</option>
<option value="tokay gecko">Tokay gecko</option>
<option value="topi">Topi</option>
<option value="tortoise, asian foreset">Tortoise, asian foreset</option>
<option value="tortoise, burmese black mountain">Tortoise, burmese black mountain</option>
<option value="tortoise, burmese brown mountain">Tortoise, burmese brown mountain</option>
<option value="tortoise, desert">Tortoise, desert</option>
<option value="tortoise, galapagos">Tortoise, galapagos</option>
<option value="tortoise, indian star">Tortoise, indian star</option>
<option value="tortoise, radiated">Tortoise, radiated</option>
<option value="toucan, red-billed">Toucan, red-billed</option>
<option value="toucan, white-throated">Toucan, white-throated</option>
<option value="tree porcupine">Tree porcupine</option>
<option value="tropical buckeye butterfly">Tropical buckeye butterfly</option>
<option value="trotter, lily">Trotter, lily</option>
<option value="trumpeter swan">Trumpeter swan</option>
<option value="trumpeter, dark-winged">Trumpeter, dark-winged</option>
<option value="trumpeter, green-winged">Trumpeter, green-winged</option>
<option value="tsessebe">Tsessebe</option>
<option value="turaco, violet-crested">Turaco, violet-crested</option>
<option value="turkey vulture">Turkey vulture</option>
<option value="turkey, australian brush">Turkey, australian brush</option>
<option value="turkey, common">Turkey, common</option>
<option value="turkey, wild">Turkey, wild</option>
<option value="turtle (unidentified)">Turtle (unidentified)</option>
<option value="turtle, eastern box">Turtle, eastern box</option>
<option value="turtle, long-necked">Turtle, long-necked</option>
<option value="turtle, snake-necked">Turtle, snake-necked</option>
<option value="two-banded monitor">Two-banded monitor</option>
<option value="two-toed sloth">Two-toed sloth</option>
<option value="two-toed tree sloth">Two-toed tree sloth</option>
<option value="tyrant flycatcher">Tyrant flycatcher</option>
<option value="uinta ground squirrel">Uinta ground squirrel</option>
<option value="urial">Urial</option>
<option value="verreaux's sifaka">Verreaux's sifaka</option>
<option value="vervet monkey">Vervet monkey</option>
<option value="vicuna">Vicuna</option>
<option value="vine snake (unidentified)">Vine snake (unidentified)</option>
<option value="violet-crested turaco">Violet-crested turaco</option>
<option value="violet-eared waxbill">Violet-eared waxbill</option>
<option value="viper, egyptian">Viper, egyptian</option>
<option value="vulture, bengal">Vulture, bengal</option>
<option value="vulture, black">Vulture, black</option>
<option value="vulture, egyptian">Vulture, egyptian</option>
<option value="vulture, griffon">Vulture, griffon</option>
<option value="vulture, king">Vulture, king</option>
<option value="vulture, lappet-faced">Vulture, lappet-faced</option>
<option value="vulture, oriental white-backed">Vulture, oriental white-backed</option>
<option value="vulture, turkey">Vulture, turkey</option>
<option value="vulture, white-headed">Vulture, white-headed</option>
<option value="vulture, white-rumped">Vulture, white-rumped</option>
<option value="wagtail, african pied">Wagtail, african pied</option>
<option value="wallaby, agile">Wallaby, agile</option>
<option value="wallaby, bennett's">Wallaby, bennett's</option>
<option value="wallaby, dama">Wallaby, dama</option>
<option value="wallaby, euro">Wallaby, euro</option>
<option value="wallaby, red-necked">Wallaby, red-necked</option>
<option value="wallaby, river">Wallaby, river</option>
<option value="wallaby, tammar">Wallaby, tammar</option>
<option value="wallaby, whip-tailed">Wallaby, whip-tailed</option>
<option value="wallaroo, common">Wallaroo, common</option>
<option value="wambenger, red-tailed">Wambenger, red-tailed</option>
<option value="wapiti, elk,">Wapiti, elk,</option>
<option value="warthog">Warthog</option>
<option value="water legaan">Water legaan</option>
<option value="water moccasin">Water moccasin</option>
<option value="water monitor">Water monitor</option>
<option value="waterbuck, common">Waterbuck, common</option>
<option value="waterbuck, defassa">Waterbuck, defassa</option>
<option value="wattled crane">Wattled crane</option>
<option value="waved albatross">Waved albatross</option>
<option value="waxbill, black-cheeked">Waxbill, black-cheeked</option>
<option value="waxbill, blue">Waxbill, blue</option>
<option value="waxbill, violet-eared">Waxbill, violet-eared</option>
<option value="weaver, chestnut">Weaver, chestnut</option>
<option value="weaver, lesser masked">Weaver, lesser masked</option>
<option value="weaver, red-billed buffalo">Weaver, red-billed buffalo</option>
<option value="weaver, sociable">Weaver, sociable</option>
<option value="weaver, white-browed sparrow">Weaver, white-browed sparrow</option>
<option value="weeper capuchin">Weeper capuchin</option>
<option value="western bearded dragon">Western bearded dragon</option>
<option value="western grey kangaroo">Western grey kangaroo</option>
<option value="western lowland gorilla">Western lowland gorilla</option>
<option value="western palm tanager (unidentified)">Western palm tanager (unidentified)</option>
<option value="western patch-nosed snake">Western patch-nosed snake</option>
<option value="western pygmy possum">Western pygmy possum</option>
<option value="western spotted skunk">Western spotted skunk</option>
<option value="whale, baleen">Whale, baleen</option>
<option value="whale, killer">Whale, killer</option>
<option value="whale, long-finned pilot">Whale, long-finned pilot</option>
<option value="whale, southern right">Whale, southern right</option>
<option value="whip-tailed wallaby">Whip-tailed wallaby</option>
<option value="white rhinoceros">White rhinoceros</option>
<option value="white spoonbill">White spoonbill</option>
<option value="white stork">White stork</option>
<option value="white-bellied sea eagle">White-bellied sea eagle</option>
<option value="white-browed owl">White-browed owl</option>
<option value="white-browed sparrow weaver">White-browed sparrow weaver</option>
<option value="white-cheeked pintail">White-cheeked pintail</option>
<option value="white-eye, cape">White-eye, cape</option>
<option value="white-eye, pale">White-eye, pale</option>
<option value="white-faced tree rat">White-faced tree rat</option>
<option value="white-faced whistling duck">White-faced whistling duck</option>
<option value="white-fronted bee-eater">White-fronted bee-eater</option>
<option value="white-fronted capuchin">White-fronted capuchin</option>
<option value="white-headed vulture">White-headed vulture</option>
<option value="white-lipped peccary">White-lipped peccary</option>
<option value="white-mantled colobus">White-mantled colobus</option>
<option value="white-necked raven">White-necked raven</option>
<option value="white-necked stork">White-necked stork</option>
<option value="white-nosed coatimundi">White-nosed coatimundi</option>
<option value="white-rumped vulture">White-rumped vulture</option>
<option value="white-tailed deer">White-tailed deer</option>
<option value="white-tailed jackrabbit">White-tailed jackrabbit</option>
<option value="white-throated kingfisher">White-throated kingfisher</option>
<option value="white-throated monitor">White-throated monitor</option>
<option value="white-throated robin">White-throated robin</option>
<option value="white-throated toucan">White-throated toucan</option>
<option value="white-winged black tern">White-winged black tern</option>
<option value="white-winged dove">White-winged dove</option>
<option value="white-winged tern">White-winged tern</option>
<option value="wild boar">Wild boar</option>
<option value="wild turkey">Wild turkey</option>
<option value="wild water buffalo">Wild water buffalo</option>
<option value="wildebeest, blue">Wildebeest, blue</option>
<option value="wolf spider">Wolf spider</option>
<option value="wolf, common">Wolf, common</option>
<option value="wolf, mexican">Wolf, mexican</option>
<option value="wolf, timber">Wolf, timber</option>
<option value="wombat, common">Wombat, common</option>
<option value="wombat, southern hairy-nosed">Wombat, southern hairy-nosed</option>
<option value="wood pigeon">Wood pigeon</option>
<option value="woodchuck">Woodchuck</option>
<option value="woodcock, american">Woodcock, american</option>
<option value="woodpecker, downy">Woodpecker, downy</option>
<option value="woodpecker, red-headed">Woodpecker, red-headed</option>
<option value="woodrat (unidentified)">Woodrat (unidentified)</option>
<option value="woolly-necked stork">Woolly-necked stork</option>
<option value="worm snake (unidentified)">Worm snake (unidentified)</option>
<option value="woylie">Woylie</option>
<option value="yak">Yak</option>
<option value="yellow baboon">Yellow baboon</option>
<option value="yellow mongoose">Yellow mongoose</option>
<option value="yellow-bellied marmot">Yellow-bellied marmot</option>
<option value="yellow-billed hornbill">Yellow-billed hornbill</option>
<option value="yellow-billed stork">Yellow-billed stork</option>
<option value="yellow-brown sungazer">Yellow-brown sungazer</option>
<option value="yellow-crowned night heron">Yellow-crowned night heron</option>
<option value="yellow-headed caracara">Yellow-headed caracara</option>
<option value="yellow-necked spurfowl">Yellow-necked spurfowl</option>
<option value="yellow-rumped siskin">Yellow-rumped siskin</option>
<option value="yellow-throated sandgrouse">Yellow-throated sandgrouse</option>
<option value="zebra, common">Zebra, common</option>
<option value="zebra, plains">Zebra, plains</option>
<option value="zorilla">Zorilla</option>
<option value="zorro, azara's">Zorro, azara's</option>
<option value="zorro, common">Zorro, common</option>
            </select>
          <p>Animal</p>
            <input name = "Animal">
          <p>Image</p>
				<input type="file" name="file"><br><br>
                <input id="la" name="la" value = "0" hidden >
                <input id="lo" name="lo" value = "0" hidden >
                <input id="userId" name="userId" value = '<?php echo $uid ?>' hidden >
				<input type="submit" value="Submit">
                

          </form>
        </div>
      </div>
    </div>
        
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" name="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="img/w3newbie.png"></a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="#">Home</a></li>
              <li><a id="buttonAdd">Add</a><li>
              <li><a href="./about/">About</a></li>
              <li><a href="<?php if ($_SESSION['logged_in']) { echo "../account/profile/"; } ?>">Profile</a></li>
              <li><a href="<?php echo $href ?>"><?php echo $value ?></a></li>
            </ul>
        </div>
        </div>
      </nav>
        
    </body>
    
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
       integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log=="
       crossorigin=""></script>
     <div id="mapid"></div>
    <p id="demo"></p>
    <?php
    $servername = "xq7t6tasopo9xxbs.cbetxkdyhwsb.us-east-1.rds.amazonaws.com";
    $username = "pm3gaxazmj304hlq";
    $password = "ob6dpkek4vwj75w7";
    $dbname = "ou71kwcm2qpd3o88";

    // Create connection
    $conn = new mysqli($servername, $username, $password, $dbname);
    // Check connection
    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    } 
    $result = $conn->query("SELECT lat,longitude FROM sightings;");
                  
    ?>
    <script>

    getLocation();    
    var x = document.getElementById("demo");
    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(startMapOnCurrentPosistion);
        } else {
            x.innerHTML = "Geolocation is not supported by this browser.";
        }
    }
        
    function startMapOnCurrentPosistion(position) {
        var la = position.coords.latitude;
        var lo = position.coords.latitude;
        var mymap = L.map('mapid').setView([la, position.coords.longitude], 13);
        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.streets-satellite',
        accessToken: 'pk.eyJ1IjoiYW5kY2FzdCIsImEiOiJjajl2cmx6OHQxYzZwMnJwYzd6MGx4YTBzIn0.Rio1VOW1ZAVkCxwZ2Oz2NQ'
    }).addTo(mymap);
        <?php
        if ($result->num_rows > 0) {
        // output data of each row
        while($row = $result->fetch_assoc()) {?>
             var marker = L.marker([<?php echo $row["lat"]?>,<?php echo $row["longitude"]?>]).addTo(mymap);
        <?php
        }
    } else {
            echo "0 results";
    } ?>
   }
        
    // Get the modal
    var modal = document.getElementById('myModal');

    // Get the button that opens the modal
    var btn = document.getElementById("buttonAdd");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on the button, open the modal 
    btn.onclick = function() {
        modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }

    </script>
    
</html>
